services:
  filedpapers-web:
    image: ghcr.io/svenkubiak/filedpapers/filedpapers:${VERSION}
    container_name: filedpapers-web
    restart: always
    environment:
      JAVA_OPTS: >
        -Dapplication.url=${APPLICATION_URL}
        -Dapplication.config=/app/config/config.yaml
        -Dapplication.secret=${APPLICATION_SECRET}
        -Dapi.accessToken.secret=${ACCESS_TOKEN_SECRET}
        -Dapi.refreshToken.secret=${REFRESH_TOKEN_SECRET}
        -Dapi.challengeToken.secret=${CHALLENGE_TOKEN_SECRET}
        -Dsession.cookie.secret=${SESSION_SECRET}
        -Dauthentication.cookie.secret=${AUTHENTICATION_SECRET}
        -Dflash.cookie.secret=${FLASH_SECRET}
        -Dapplication.registration=${ALLOW_REGISTRATION}
        -Dpersistence.mongo.dbname=${MONGODB_INITDB_DATABASE}
        -Dpersistence.mongo.username=${MONGODB_INITDB_ROOT_USERNAME}
        -Dpersistence.mongo.password=${MONGODB_INITDB_ROOT_PASSWORD}
        -Dsmtp.host=${SMTP_HOST}
        -Dsmtp.port=${SMTP_PORT}
        -Dsmtp.authentication=${SMTP_AUTHENTICATION}
        -Dsmtp.username=${SMTP_USERNAME}
        -Dsmtp.password=${SMTP_PASSWORD}
        -Dsmtp.from=${SMTP_FROM}
        -Dsmtp.protocol=${SMTP_PROTOCOL}
        -Dsmtp.debug=${SMTP_DEBUG}    
        -Xms256m
        -Xmx1024m
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config:/app/config
      - ./logs:/logs
    depends_on:
      filedpapers-database:
        condition: service_healthy
      filedpapers-metascraper:
        condition: service_healthy
    networks:
      - filedpapers-network

  filedpapers-database:
    image: mongodb/mongodb-community-server:latest
    container_name: filedpapers-database
    restart: always
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
      - MONGODB_INITDB_DATABASE=${MONGODB_INITDB_DATABASE}
    volumes:
      - filed_papers_mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - filedpapers-network

  filedpapers-metascraper:
    container_name: filedpapers-metascraper
    image: ghcr.io/svenkubiak/filedpapers/filedpapers-metascraper:${VERSION}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - filedpapers-network

networks:
  filedpapers-network:
    driver: bridge

volumes:
  filed_papers_mongodb_data: