services:
  filepapers-backend:
    container_name: filedpapers-backend
    image: ghcr.io/svenkubiak/filedpapers/filedpapers:1.0.0-alpha1
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config:/app/config
    environment:
      - JAVA_OPTS=-Dapplication.config=/app/config/config.yaml -Xms256m -Xmx1024m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - filepapers-database
    networks:
      - app-network

  filepapers-database:
    image: mongo:latest
    container_name: filedpapers-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: filedpapers
      MONGO_INITDB_ROOT_PASSWORD: filedpapers
      MONGO_INITDB_DATABASE: filedpapers
    command: ["mongod", "--bind_ip", "0.0.0.0"]
    volumes:
      - mongodb_data:/data/db
    networks:
     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: