services:
  filedpapers-web:
    container_name: filedpapers-web
    image: ghcr.io/svenkubiak/filedpapers/filedpapers:1.0.0-alpha3
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config:/app/config
    environment:
      - JAVA_OPTS=-Dapplication.config=/app/config/config.yaml -Xms256m -Xmx1024m
    depends_on:
      - filedpapers-database
    networks:
      - filedpapers-network

  filedpapers-database:
    image: mongodb/mongodb-community-server:8.0.4-ubuntu2204
    container_name: filedpapers-database
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
      - MONGODB_INITDB_DATABASE=${MONGODB_INITDB_DATABASE}
    volumes:
      - fp_mongodb_data:/data/db
    networks:
      - filedpapers-network

networks:
  filedpapers-network:
    driver: bridge

volumes:
  fp_mongodb_data: