### Do not change anything unless you know what you are doing ###

default:
  application:
    language: en
    url: arg{}
    secret: arg{}
    registration: arg{}
  connector:
    http:
      host: filedpapers-web
      port: 9090
  api:
    accessToken:
      secret: arg{}
      expires: 60
    refreshToken:
      secret: arg{}
      expires: 10080
    challengeToken:
      secret: arg{}
  session:
    cookie:
      name: __Host-filedpapers-session
      secret: arg{}
      secure: true
  authentication:
    redirect:
      login: /auth/login
      mfa: /auth/mfa
    cookie:
      name: __Host-filedpapers-authentication
      secret: arg{}
      secure: true
  flash:
    cookie:
      name: __Host-filedpapers-flash
      secret: arg{}
      secure: true
  i18n:
    cookie:
      name: __Host-filedpapers-i18n
  smtp:
    host: arg{}
    port: arg{}
    authentication: arg{}
    username: arg{}
    password: arg{}
    from: arg{}
    protocol: arg{}
    debug: arg{}
  persistence:
    mongo:
      embedded: false
      host: filedpapers-database
      port: 27017
      dbname: filedpapers
      username: arg{}
      password: arg{}
      authdb: admin
      auth: true
      package: models

environments:
  prod:
    application:
      name: filedpapers

### Do not change anything unless you know what you are doing ###