name: Build, Dockerize, Scan

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'feature/**'

jobs:
  docker-root:
    name: Filedpaper App Docker & Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '25'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image (root)
        run: docker build -t my-app-root:latest .

      - name: Trivy scan (root)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: my-app-root:latest
          format: table
          exit-code: '1'
          ignore-unfixed: false
          severity: LOW,MEDIUM,CRITICAL,HIGH


  docker-metascraper:
    name: Filedpaper Metascraper Docker & Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: metascraper/package-lock.json

      - name: Install dependencies
        working-directory: metascraper
        run: npm install

      - name: Build metascraper app
        working-directory: metascraper
        run: npm run build

      - name: Build Docker image (metascraper)
        run: docker build -t my-app-metascraper:latest -f metascraper/Dockerfile .

      - name: Trivy scan (metascraper)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: my-app-metascraper:latest
          format: table
          exit-code: '1'
          ignore-unfixed: false
          severity: LOW,MEDIUM,HIGH,CRITICAL

