name: Update Version Badges and GHCR Links

on:
  push:
    tags:
      - "*"

jobs:
  update-badges-and-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get tags from GHCR
      run: |
        # Fetch all tags from GHCR with authentication and capture both output and HTTP status
        response=$(curl -s -w "%{http_code}" -H "Authorization: Bearer $GITHUB_TOKEN" "https://ghcr.io/v2/svenkubiak/filedpapers/tags/list")
        http_code=$(echo "$response" | tail -n 1)  # Extract the HTTP status code
        body=$(echo "$response" | head -n -1)     # Extract the response body (without the status code)

        # Print the raw response and the status code for debugging
        echo "HTTP Status Code: $http_code"
        echo "Raw GHCR Response: $body"

        # Check if the status code is 200 (OK)
        if [ "$http_code" -eq 200 ]; then
          echo "Request succeeded, processing tags..."
          # Parse tags from the JSON response
          TAGS=$(echo "$body" | jq -r '.tags[]')

          # Filter out alpha, beta, and rc versions for the stable version (case-insensitive)
          STABLE_VERSION=$(echo "$TAGS" | grep -viE 'alpha|beta|rc' | sort -V | tail -n 1)

          # Include alpha, beta, and rc versions for the development version (case-insensitive)
          DEV_VERSION=$(echo "$TAGS" | grep -iE 'alpha|beta|rc' | sort -V | tail -n 1)

          # Set the versions as environment variables
          echo "STABLE_VERSION=$STABLE_VERSION" >> $GITHUB_ENV
          echo "DEV_VERSION=$DEV_VERSION" >> $GITHUB_ENV
        else
          echo "Request failed with HTTP code $http_code"
          exit 1
        fi

    - name: Update README with badges and GHCR links
      run: |
        # Generate the badge URLs
        STABLE_BADGE_URL="https://img.shields.io/badge/version-$STABLE_VERSION-brightgreen"
        DEV_BADGE_URL="https://img.shields.io/badge/version-$DEV_VERSION-blue"

        # Generate GHCR URLs for stable and dev versions
        STABLE_GHCR_URL="https://github.com/svenkubiak/filedpapers/pkgs/container/filedpapers%2Ffiledpapers?tag=$STABLE_VERSION"
        DEV_GHCR_URL="https://github.com/svenkubiak/filedpapers/pkgs/container/filedpapers%2Ffiledpapers?tag=$DEV_VERSION"

        # Update the README with both badges and GHCR links
        sed -i "s|https://img.shields.io/badge/version-.*stable|$STABLE_BADGE_URL|g" README.md
        sed -i "s|https://img.shields.io/badge/version-.*dev|$DEV_BADGE_URL|g" README.md
        sed -i "s|https://github.com/svenkubiak/filedpapers/pkgs/container/filedpapers%2Ffiledpapers?tag=latest|$STABLE_GHCR_URL|g" README.md
        sed -i "s|https://github.com/svenkubiak/filedpapers/pkgs/container/filedpapers%2Ffiledpapers?tag=latest|$DEV_GHCR_URL|g" README.md

    - name: Commit changes to README
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m "Update version badges and GHCR links"
        git push
